apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-back
  template:
    metadata:
      labels:
        app: java-back
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: java-back
        image: registryidq6940.azurecr.io/user-java:latest # image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: SQL_USER	
          value: "sqladminiDq6940"
        - name: SQL_PASSWORD
          value: "Password123!"
        - name: SQL_SERVER
          value: 'sqlserveridq6940.database.windows.net'
        - name: SQL_DBNAME
          value: "mydrivingDB"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 80 # set container to listn on port 8080
          name: java-back
---
apiVersion: v1
kind: Service
metadata:
  name: java-back-ingress
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # map ingress port 80 to container port 80
  selector:
    app: java-back