apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi-app
  template:
    metadata:
      labels:
        app: poi-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: poi-app
        image: registryidq6940.azurecr.io/userprofile:latest # image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: PORT
          valeu: '1433'
        - name: SQL_USER	
          value: "sqladminiDq6940"
        - name: SQL_PASSWORD
          value: "Password123!"
        - name: SQL_SERVER
          value: 'sqlserveridq6940.database.windows.net:1433'
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: CREDENTIAL_METHOD
          value: "yes"
        - name: IDENTITY_CLIENT_ID
          value: "yes"
        - name: OPENAPI_DOCS_URI
          value: "yes"
        - name: DEBUG_LOGGING
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
          name: poi-app
---
apiVersion: v1
kind: Service
metadata:
  name: openhack-poi-ingress
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: poi-app