apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  SQL_SERVER: sqlserveridq6940.database.windows.net
  SQL_USER: sqladminiDq6940
  SQL_PASSWORD: Password123!
  SQL_DBNAME: mydrivingDB