name: Deploy-POI

on:  
  workflow_dispatch:
env:
  DOCKERFILE_PATH: './dockerfiles'
  DOCKER_IMAGE_NAME: 'poi'


jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://registryidq6940.azurecr.io/
        username: 'registryidq6940'
        password: 'OpOimuG4qYVoeWAnJvqn19iTghCBPR6ElPEhc4VR6d+ACRDkuTzC'
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: registryidq6940.azurecr.io/${{env.DOCKER_IMAGE_NAME}}:latest
        file: ./dockerfiles/Dockerfile_3
