name: deploy-aks

on:
  workflow_dispatch:
env:
  DOCKERFILE_PATH: './dockerfiles/'
  DOCKER_IMAGE_NAME: 'tripviewer'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2
      
    - name: Log in to ACR
      uses: docker/login-action@v1
      with:
        registry: https://registryidq6940.azurecr.io
        username: 'registryidq6940'
        password: 'OpOimuG4qYVoeWAnJvqn19iTghCBPR6ElPEhc4VR6d+ACRDkuTzC'
  deploy:
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: application
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  ports:
  - port: 6379
  selector:
    app: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: application
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: container-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front
