name: Deploy-tripviewer

on:
  workflow_dispatch:
env:
  DOCKERFILE_PATH: './dockerfiles/'
  DOCKER_IMAGE_NAME: 'tripviewer'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_LOGIN }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.ACR_LOGIN }}/${{env.DOCKER_IMAGE_NAME}}:latest
        file: ./dockerfiles/Dockerfile_1
        context: ./src/tripviewer
  
