name: deploy-openhack-poi

on:
  workflow_dispatch:
env:
  DOCKERFILE_PATH: './dockerfiles/Dockerfile_3'
  DOCKER_IMAGE_NAME: 'openhack-poi'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_LOGIN }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registryidq6940.azurecr.io/${{env.DOCKER_IMAGE_NAME}}:latest
          file: ./dockerfiles/Dockerfile_3
          context: ./src/poi

  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image

    steps:
      - uses: actions/checkout@v2

      - uses: Azure/setup-helm@v1
        with:
          version: v3.3.1

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          # Azure credentials, i.e., output of `az ad sp create-for-rbac --scopes /subscriptions/<SUBSCRIPTION-ID> --role Contributor --sdk-auth`
          creds: ${{ secrets.AZ_CREDS }}
          # Resource group name
          resource-group: teamResources
          # AKS cluster name
          cluster-name: testAKSCluster
      - name: Run Helm Deploy
        run: |
          helm upgrade \
          --install \
          --create-namespace \
          --atomic \
          --wait \
          --namespace staging \
          contoso-website \
          ./kubernetes/contoso-website \
          --set image.repository=${{ secrets.ACR_NAME }} \
          --set dns.name=10.244.0.10:53
